### ISSUE TITLE
failed to build with colcon

### ISSUE THREAD

**Issue by Montecchsilvia** [micro-ROS/micro-ROS-doc#7]
The error is:
make[2]: *** [gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o] Error 1
make[2]: *** [gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [gtest/CMakeFiles/gtest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [gtest/CMakeFiles/gtest_main.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< rmw_microxrcedds	[ Exited with code 2 ]

Summary: 71 packages finished [8.63s]
  1 package failed: rmw_microxrcedds
  1 package had stderr output: rmw_microxrcedds
  48 packages not processed

**Comment by Montecchsilvia** [comment]
Hi. Yes, of course.

- Ubuntu bionic 18.04

- I only used the repos that are in the installation guide here: https://github.com/microROS/micro-ROS-doc/blob/master/docs/install_and_run.md

- No. I'm trying to install directly on my machine

- rmw_microxrcedds full error report: which log file do you mean?

**Comment by qeyup** [comment]
Hi, It seems that some gtest libraries may be missing. Can you test to compile without building test.

```bash
colcon build --cmake-args -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF
```

**Comment by qeyup** [comment]
Hi, I found that you probably missing "clang-tidy" package. install it a try to build MicroROS again.
```
sudo apt install clang-tidy
```

regards

**Comment by Montecchsilvia** [comment]
Thank you a lot for your reply. Sorry I'm late but I didn't see your reply.
I'm in trouble with another problem, when I will solve it I will try your
suggestions.
Thank you,
Silvia

Il giorno ven 30 nov 2018 alle ore 12:47 Javier Moreno <
notifications@github.com> ha scritto:

**Comment by BorjaOuterelo** [comment]
@Montecchsilvia I close this issue due to inactivity.
